DROP TABLE Animals CASCADE CONSTRAINTS;

CREATE TABLE Animals (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  herdId NUMBER NOT NULL,
  dateOfBirth DATE NOT NULL,
  tagNumber NUMBER NOT NULL UNIQUE,
  cattleClass VARCHAR2(255) NOT NULL,
  status VARCHAR2(255),
  comments VARCHAR2(500),
  CONSTRAINT fk_herd FOREIGN KEY (herdId)
    REFERENCES Herds(id)
    ON DELETE SET NULL
);

CREATE OR REPLACE TRIGGER increment_headsize
AFTER INSERT ON Animals
FOR EACH ROW
BEGIN
  UPDATE Herds
  SET headSize = headSize + 1
  WHERE id = :NEW.herdId;
END;
/

CREATE OR REPLACE TRIGGER decrement_headsize
AFTER DELETE ON Animals
FOR EACH ROW
BEGIN
  UPDATE Herds
  SET headSize = headSize - 1
  WHERE id = :OLD.herdId;
END;
/

CREATE OR REPLACE TRIGGER update_headsize
AFTER UPDATE OF herdId ON Animals
FOR EACH ROW
BEGIN
  IF :OLD.herdId IS NOT NULL THEN
    UPDATE Herds
    SET headSize = headSize - 1
    WHERE id = :OLD.herdId;
  END IF;

  IF :NEW.herdId IS NOT NULL THEN
    UPDATE Herds
    SET headSize = headSize + 1
    WHERE id = :NEW.herdId;
  END IF;
END;
/
